// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedFinanceConsoleDB.Database;

#nullable disable

namespace SharedFinanceConsoleDB.Database.Migrations
{
    [DbContext(typeof(SharedFinanceDBContext))]
    [Migration("20260510211811_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CounterpartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CounterpartyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Account", b =>
                {
                    b.HasOne("SharedFinanceConsoleDB.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Transaction", b =>
                {
                    b.HasOne("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Account", "Counterparty")
                        .WithMany("CounterpartyTransactions")
                        .HasForeignKey("CounterpartyId");

                    b.Navigation("Account");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("SharedFinanceConsoleDB.Domain.Aggregates.AccountAggregate.Account", b =>
                {
                    b.Navigation("CounterpartyTransactions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
